#!/usr/bin/env bash
# Install the event-driven systemd battery-care policy.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
# shellcheck source=../config.sh
source "$ROOT/config.sh"

[[ $EUID -eq 0 ]] || { echo "Please run as root: sudo -E systemd/install.sh" >&2; exit 1; }
command -v systemctl >/dev/null || { echo "systemctl is required." >&2; exit 1; }

valid_hour() { [[ "$1" =~ ^([01]?[0-9]|2[0-3])$ ]]; }
valid_percent() { [[ "$1" =~ ^[0-9]{1,3}$ ]] && (( 10#$1 <= 100 )); }
valid_workdays() { [[ "$1" == "*" || "$1" =~ ^[0-7](-[0-7])?(,[0-7](-[0-7])?)*$ ]]; }

for value in "$NIGHT_HOUR" "$MORNING_HOUR"; do valid_hour "$value" || { echo "Hours must be 0-23." >&2; exit 1; }; done
for value in "$NIGHT_DISCHARGE_TARGET" "$NIGHT_START_THRESHOLD" "$NIGHT_STOP_THRESHOLD" "$DAY_START_THRESHOLD" "$DAY_STOP_THRESHOLD"; do valid_percent "$value" || { echo "Thresholds must be percentages from 0 to 100." >&2; exit 1; }; done
(( NIGHT_START_THRESHOLD <= NIGHT_STOP_THRESHOLD && DAY_START_THRESHOLD <= DAY_STOP_THRESHOLD )) || { echo "Start thresholds must not exceed stop thresholds." >&2; exit 1; }
(( MORNING_HOUR < NIGHT_HOUR )) || { echo "MORNING_HOUR must be earlier than NIGHT_HOUR for the overnight policy." >&2; exit 1; }
[[ "$NIGHT_DISCHARGE_MAX_RUNTIME_MINUTES" =~ ^[1-9][0-9]*$ ]] || { echo "NIGHT_DISCHARGE_MAX_RUNTIME_MINUTES must be a positive integer." >&2; exit 1; }
valid_workdays "$WORKDAYS" || { echo "WORKDAYS must be *, or comma-separated 0-7 values/ranges (e.g. 1-5)." >&2; exit 1; }

TLP_BIN="$(command -v tlp 2>/dev/null || true)"
[[ -z "$TLP_BIN" && -x /usr/sbin/tlp ]] && TLP_BIN=/usr/sbin/tlp
[[ -n "$TLP_BIN" ]] || { echo "tlp not found; install TLP first." >&2; exit 1; }

SYS="/sys/class/power_supply/${BATTERY}"
[[ -e "$SYS" ]] || { echo "Battery '${BATTERY}' not found under /sys/class/power_supply/." >&2; exit 1; }
[[ -e "$SYS/charge_behaviour" ]] || echo "WARNING: charge_behaviour is missing; low thresholds will work but forced discharge may not." >&2

BIN_DIR="${INSTALL_BIN_DIR%/}"
UD="${UNIT_DIR%/}"
RD="${RUNTIME_DIR%/}"
SLEEP_DIR="${SYSTEM_SLEEP_DIR%/}"
DISCHARGE="$BIN_DIR/battery-discharge-to.sh"
POLICY="$BIN_DIR/battery-care-policy.sh"
RUNTIME_CONFIG="$RD/battery-care.conf"
SLEEP_HOOK="$SLEEP_DIR/battery-care"
RUNTIME_SECONDS=$((NIGHT_DISCHARGE_MAX_RUNTIME_MINUTES * 60))

install -D -m 0755 "$ROOT/bin/battery-discharge-to.sh" "$DISCHARGE"
install -D -m 0755 "$ROOT/bin/battery-care-policy.sh" "$POLICY"
mkdir -p "$RD" "$UD" "$SLEEP_DIR"

# The policy sources this file; keep it root-owned and shell-escaped.
{
    echo "# Generated by systemd/install.sh; edit config.sh and reinstall."
    for name in BATTERY NIGHT_DISCHARGE_TARGET NIGHT_START_THRESHOLD NIGHT_STOP_THRESHOLD DAY_START_THRESHOLD DAY_STOP_THRESHOLD NIGHT_HOUR MORNING_HOUR WORKDAYS; do
        printf '%s=%q\n' "$name" "${!name}"
    done
    printf 'TLP_BIN=%q\nDISCHARGE_BIN=%q\n' "$TLP_BIN" "$DISCHARGE"
} > "$RUNTIME_CONFIG"
chmod 0600 "$RUNTIME_CONFIG"

printf -v NIGHT_HH '%02d' "$NIGHT_HOUR"
printf -v MORNING_HH '%02d' "$MORNING_HOUR"
cron_dow_to_systemd() {
    local spec="$1" part a b i out=""; local -a names=(Sun Mon Tue Wed Thu Fri Sat) parts
    [[ "$spec" == "*" ]] && { printf '%s' '*-*-*'; return; }
    IFS=',' read -ra parts <<< "$spec"
    for part in "${parts[@]}"; do
        if [[ "$part" == *-* ]]; then
            a="${part%-*}"; b="${part#*-}"; (( a == 7 )) && a=0; (( b == 7 )) && b=0
            out+="${out:+,}${names[a]}..${names[b]}"
        else
            i="$part"; (( i == 7 )) && i=0; out+="${out:+,}${names[i]}"
        fi
    done
    printf '%s' "$out"
}
WORKDAYS_CAL="$(cron_dow_to_systemd "$WORKDAYS")"

header() { cat <<EOF
# Generated from config.sh by systemd/install.sh. Do not hand-edit.
EOF
}

{ header; cat <<EOF
[Unit]
Description=Battery care policy reconciler

[Service]
Type=oneshot
ExecStart=${POLICY} reconcile
EOF
} > "$UD/battery-care-reconcile.service"

{ header; cat <<EOF
[Unit]
Description=Battery care bounded low-charge discharge
Before=sleep.target suspend.target hibernate.target hybrid-sleep.target
Conflicts=sleep.target suspend.target hibernate.target hybrid-sleep.target

[Service]
Type=exec
TimeoutStartSec=${RUNTIME_SECONDS}
TimeoutStopSec=30
ExecStart=${POLICY} discharge
EOF
} > "$UD/battery-care-low.service"

{ header; cat <<EOF
[Unit]
Description=Battery care low-interval boundary

[Timer]
OnCalendar=*-*-* ${NIGHT_HH}:00:00
Persistent=true

[Install]
WantedBy=timers.target
EOF
} > "$UD/battery-care-night.timer"

{ header; cat <<EOF
[Unit]
Description=Battery care normal-interval boundary

[Timer]
OnCalendar=${WORKDAYS_CAL} ${MORNING_HH}:00:00
Persistent=true

[Install]
WantedBy=timers.target
EOF
} > "$UD/battery-care-morning.timer"

for timer in night morning; do
    { header; cat <<EOF
[Unit]
Description=Battery care ${timer} boundary reconciliation

[Service]
Type=oneshot
ExecStart=${SYSTEMCTL_BIN:-/usr/bin/systemctl} start battery-care-reconcile.service
EOF
    } > "$UD/battery-care-${timer}.service"
done

{ header; cat <<EOF
[Unit]
Description=Battery care departure guard
DefaultDependencies=no
Before=battery-care-reconcile.service battery-care-low.service shutdown.target
Conflicts=shutdown.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/true
ExecStop=${POLICY} departure shutdown
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target
EOF
} > "$UD/battery-care-departure.service"

cat > "$SLEEP_HOOK" <<EOF
#!/usr/bin/env bash
# Generated by tlp-battery-care. Invoked by systemd-sleep(8).
case "\${1:-}" in
    pre)  ${POLICY} departure "\${2:-sleep}" ;;
    post) /usr/bin/systemctl start --no-block battery-care-reconcile.service ;;
esac
EOF
chmod 0755 "$SLEEP_HOOK"
chmod 0644 "$UD"/battery-care-*.service "$UD"/battery-care-*.timer

systemctl daemon-reload
systemctl enable --now battery-care-night.timer battery-care-morning.timer battery-care-departure.service
systemctl start battery-care-reconcile.service

echo "Installed event-driven battery care."
echo "Status: systemctl status battery-care-reconcile.service battery-care-low.service"
echo "Logs:   journalctl -t battery-care --since today"
